run:
  deadline: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - lll
    - maligned
    - wsl
  fast: false
