version: "3.7"
services:
  bert:
    image: registry.gitlab.com/rostepifanov/mca-workshop:model-wrapper-bert
    container_name: mca_workshop_bert
    restart: always
    environment:
      - MCA_WORKSHOP_LISTEN_HOST=0.0.0.0
      - MCA_WORKSHOP_MODEL_PATH=/srv/models/bertmodel.pkl.notebook
      - LC_ALL=en_US.UTF-8
      - TRANSFORMERS_CACHE=/srv/bert/

  elmo:
    image: registry.gitlab.com/rostepifanov/mca-workshop:model-wrapper-elmo
    container_name: mca_workshop_elmo
    restart: always
    environment:
      - MCA_WORKSHOP_LISTEN_HOST=0.0.0.0
      - MCA_WORKSHOP_MODEL_PATH=/srv/models/elmomodel.pkl
      - LC_ALL=en_US.UTF-8

  gateway:
    image: mca_workshop_bot
    container_name: mca_workshop_gateway
    restart: always
    env_file: .env
    links:
      - "bert:bert"
      - "elmo:elmo"
